/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/public'
import { Route as PrivateRouteImport } from './routes/private'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicIndexRouteImport } from './routes/public/index'
import { Route as PrivateIndexRouteImport } from './routes/private/index'
import { Route as PrivateUsersRouteImport } from './routes/private/users'
import { Route as PrivateFormRouteImport } from './routes/private/form'

const PublicRoute = PublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/private',
  path: '/private',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateUsersRoute = PrivateUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateFormRoute = PrivateFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => PrivateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/private': typeof PrivateRouteWithChildren
  '/public': typeof PublicRouteWithChildren
  '/private/form': typeof PrivateFormRoute
  '/private/users': typeof PrivateUsersRoute
  '/private/': typeof PrivateIndexRoute
  '/public/': typeof PublicIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/private/form': typeof PrivateFormRoute
  '/private/users': typeof PrivateUsersRoute
  '/private': typeof PrivateIndexRoute
  '/public': typeof PublicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/private': typeof PrivateRouteWithChildren
  '/public': typeof PublicRouteWithChildren
  '/private/form': typeof PrivateFormRoute
  '/private/users': typeof PrivateUsersRoute
  '/private/': typeof PrivateIndexRoute
  '/public/': typeof PublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/private'
    | '/public'
    | '/private/form'
    | '/private/users'
    | '/private/'
    | '/public/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/private/form' | '/private/users' | '/private' | '/public'
  id:
    | '__root__'
    | '/'
    | '/private'
    | '/public'
    | '/private/form'
    | '/private/users'
    | '/private/'
    | '/public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/public': {
      id: '/public'
      path: '/public'
      fullPath: '/public'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private': {
      id: '/private'
      path: '/private'
      fullPath: '/private'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/': {
      id: '/public/'
      path: '/'
      fullPath: '/public/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/private/': {
      id: '/private/'
      path: '/'
      fullPath: '/private/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/private/users': {
      id: '/private/users'
      path: '/users'
      fullPath: '/private/users'
      preLoaderRoute: typeof PrivateUsersRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/private/form': {
      id: '/private/form'
      path: '/form'
      fullPath: '/private/form'
      preLoaderRoute: typeof PrivateFormRouteImport
      parentRoute: typeof PrivateRoute
    }
  }
}

interface PrivateRouteChildren {
  PrivateFormRoute: typeof PrivateFormRoute
  PrivateUsersRoute: typeof PrivateUsersRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateFormRoute: PrivateFormRoute,
  PrivateUsersRoute: PrivateUsersRoute,
  PrivateIndexRoute: PrivateIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
